#!/bin/bash
# Yeh script saari app icons/backgrounds ek hi baar download kar ke
# app/src/main/assets/img/ mein daal deti hai. Achi internet speed
# wali jagah (WiFi/friend's phone/cafe) par is folder (voiceparty/) ke andar chalayein:
#   bash download_images.sh
set -e
OUT="app/src/main/assets/img"
mkdir -p "$OUT"
curl -sL --retry 3 -o "$OUT/shop-cart.png" "https://i.postimg.cc/25MSqCsp/shop-cart.png"
curl -sL --retry 3 -o "$OUT/Chat.png" "https://i.postimg.cc/3N3069rb/Chat.png"
curl -sL --retry 3 -o "$OUT/file-00000000229c81fd83b90d22a29f7bba.png" "https://i.postimg.cc/3wJwRhbG/file-00000000229c81fd83b90d22a29f7bba.png"
curl -sL --retry 3 -o "$OUT/regression-coin-min-uncheck.webp" "https://i.postimg.cc/4dVpVyqR/regression-coin-min-uncheck.webp"
curl -sL --retry 3 -o "$OUT/golden-dice-big.webp" "https://i.postimg.cc/4yRBqv5L/golden-dice-big.webp"
curl -sL --retry 3 -o "$OUT/btn-associate-exit.webp" "https://i.postimg.cc/5NSyvLtn/btn-associate-exit.webp"
curl -sL --retry 3 -o "$OUT/game-bg.png" "https://i.postimg.cc/7PNMr2g7/game-bg.png"
curl -sL --retry 3 -o "$OUT/file-00000000dc8082118a379ac2ac711ac3.png" "https://i.postimg.cc/7hXMvxGY/file-00000000dc8082118a379ac2ac711ac3.png"
curl -sL --retry 3 -o "$OUT/regression-coin-min-check.webp" "https://i.postimg.cc/8CFRktbs/regression-coin-min-check.webp"
curl -sL --retry 3 -o "$OUT/room-ic-input-sound-off.webp" "https://i.postimg.cc/90GMLqY2/room-ic-input-sound-off.webp"
curl -sL --retry 3 -o "$OUT/fragment-Rule2.webp" "https://i.postimg.cc/90bQZHBN/fragment-Rule2.webp"
curl -sL --retry 3 -o "$OUT/file-000000000d188208a6a8a0921cdc4517.png" "https://i.postimg.cc/9Qm12dSP/file-000000000d188208a6a8a0921cdc4517.png"
curl -sL --retry 3 -o "$OUT/piece-red.webp" "https://i.postimg.cc/9z3TdZKM/piece-red.webp"
curl -sL --retry 3 -o "$OUT/regression-coin-add-check.webp" "https://i.postimg.cc/Bnn5kqLT/regression-coin-add-check.webp"
curl -sL --retry 3 -o "$OUT/rocket.webp" "https://i.postimg.cc/C1k4GBgr/rocket.webp"
curl -sL --retry 3 -o "$OUT/game-online-4p-uncheck.png" "https://i.postimg.cc/FzhyJrQy/game-online-4p-uncheck.png"
curl -sL --retry 3 -o "$OUT/team.png" "https://i.postimg.cc/GhRLZ7Ps/team.png"
curl -sL --retry 3 -o "$OUT/icon-golden-dice.webp" "https://i.postimg.cc/HLr8mn9K/icon-golden-dice.webp"
curl -sL --retry 3 -o "$OUT/file-0000000097f0820b81bc2995a995177d.png" "https://i.postimg.cc/HkzKxGWs/file-0000000097f0820b81bc2995a995177d.png"
curl -sL --retry 3 -o "$OUT/2.png" "https://i.postimg.cc/Hx9QPDNn/2.png"
curl -sL --retry 3 -o "$OUT/coin-icon.webp" "https://i.postimg.cc/MGQ8FVFh/coin-icon.webp"
curl -sL --retry 3 -o "$OUT/user-icon.png" "https://i.postimg.cc/MK9xMWRc/user-icon.png"
curl -sL --retry 3 -o "$OUT/tick.webp" "https://i.postimg.cc/MTxwDrHt/tick.webp"
curl -sL --retry 3 -o "$OUT/selected-light-green-glow-transparent.png" "https://i.postimg.cc/MX2VWRS7/selected-light-green-glow-transparent.png"
curl -sL --retry 3 -o "$OUT/game-online-2p-uncheck.png" "https://i.postimg.cc/QdzJnZpV/game-online-2p-uncheck.png"
curl -sL --retry 3 -o "$OUT/Events.png" "https://i.postimg.cc/RZgdT6dz/Events.png"
curl -sL --retry 3 -o "$OUT/2-4-players.png" "https://i.postimg.cc/Rh7MWKm5/2-4-players.png"
curl -sL --retry 3 -o "$OUT/rank-no-2.webp" "https://i.postimg.cc/SQX4hmGT/rank-no-2.webp"
curl -sL --retry 3 -o "$OUT/4.png" "https://i.postimg.cc/T2QVVxmV/4.png"
curl -sL --retry 3 -o "$OUT/1.png" "https://i.postimg.cc/W3vGnbXh/1.png"
curl -sL --retry 3 -o "$OUT/regression-coin-add-uncheck.webp" "https://i.postimg.cc/W4QMdg9r/regression-coin-add-uncheck.webp"
curl -sL --retry 3 -o "$OUT/diamond.png" "https://i.postimg.cc/XqcjDdp8/diamond.png"
curl -sL --retry 3 -o "$OUT/Battle.png" "https://i.postimg.cc/Y0xYqZyK/Battle.png"
curl -sL --retry 3 -o "$OUT/setting.png" "https://i.postimg.cc/Yqz0XKWF/setting.png"
curl -sL --retry 3 -o "$OUT/Social.png" "https://i.postimg.cc/ZnY0jRjd/Social.png"
curl -sL --retry 3 -o "$OUT/file-000000002f0c8211aadf26f528f26971.png" "https://i.postimg.cc/c4nzvLkH/file-000000002f0c8211aadf26f528f26971.png"
curl -sL --retry 3 -o "$OUT/piece-bule.webp" "https://i.postimg.cc/d0J2NR10/piece-bule.webp"
curl -sL --retry 3 -o "$OUT/6.png" "https://i.postimg.cc/fTrYPv8S/6.png"
curl -sL --retry 3 -o "$OUT/Checkerboard-duel7bdc5231556b.png" "https://i.postimg.cc/jjWBTmd2/Checkerboard-duel7bdc5231556b.png"
curl -sL --retry 3 -o "$OUT/3.png" "https://i.postimg.cc/kGjWqN9h/3.png"
curl -sL --retry 3 -o "$OUT/room-icon-rank-crown.webp" "https://i.postimg.cc/mkrk5s7b/room-icon-rank-crown.webp"
curl -sL --retry 3 -o "$OUT/room-ic-input-sound.webp" "https://i.postimg.cc/mr5tk4rG/room-ic-input-sound.webp"
curl -sL --retry 3 -o "$OUT/1000101592-removebg-preview.png" "https://i.postimg.cc/mrRbn4Gc/1000101592-removebg-preview.png"
curl -sL --retry 3 -o "$OUT/piece-yellow.webp" "https://i.postimg.cc/nVNwR5tV/piece-yellow.webp"
curl -sL --retry 3 -o "$OUT/game-bg.webp" "https://i.postimg.cc/qBFGBCmF/game-bg.webp"
curl -sL --retry 3 -o "$OUT/bg-add-coin.png" "https://i.postimg.cc/rmqRyVxq/bg-add-coin.png"
curl -sL --retry 3 -o "$OUT/piece-green.webp" "https://i.postimg.cc/sXXpsV5G/piece-green.webp"
curl -sL --retry 3 -o "$OUT/coin.webp" "https://i.postimg.cc/sx3GWc56/coin.webp"
curl -sL --retry 3 -o "$OUT/5.png" "https://i.postimg.cc/tCThDct8/5.png"
curl -sL --retry 3 -o "$OUT/1000100827-removebg-preview.png" "https://i.postimg.cc/vmmJCB4Z/1000100827-removebg-preview.png"
curl -sL --retry 3 -o "$OUT/plus.png" "https://i.postimg.cc/wMVzkzG4/plus.png"
curl -sL --retry 3 -o "$OUT/rank-no-1.webp" "https://i.postimg.cc/wvvWDTBV/rank-no-1.webp"
curl -sL --retry 3 -o "$OUT/system.webp" "https://i.postimg.cc/y60TSpCD/system.webp"
echo "Sab $(ls \"$OUT\" | wc -l) images download ho gayi hain assets/img/ mein."
